/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function(knex) {
  await knex.raw(`
    CREATE TABLE "Image" (
      "image_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "product_id" INTEGER,
      "image_url" varchar,
      "is_primary" boolean DEFAULT false,
      FOREIGN KEY ("product_id") REFERENCES "Product"("product_id")
    );
  `);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS "Image";
  `);
};
