/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Function to reset sequence for a given table and column
    const resetSequence = async (tableName, columnName) => {
        const result = await knex(tableName).max(columnName, { as: 'maxId' }).first();
        const maxId = result.maxId || 0;
        // For PostgreSQL generated by default as identity
        // We need to find the sequence name usually generic or specific. 
        // Safest way for IDENTITY columns in PG 10+:
        // SELECT setval(pg_get_serial_sequence('"Table"', 'column'), max)

        // Note: table names are quoted in case of case sensitivity
        await knex.raw(`SELECT setval(pg_get_serial_sequence('"${tableName}"', '${columnName}'), ${maxId})`);
    };

    try {
        await resetSequence('Role', 'role_id');
        await resetSequence('User', 'user_id');
        await resetSequence('User_Config', 'setting_id');
        await resetSequence('Customer', 'customer_id');
        await resetSequence('Membership', 'tier_id');
        await resetSequence('Category', 'category_id');
        await resetSequence('Product', 'product_id');
        await resetSequence('Voucher', 'voucher_id');
        await resetSequence('Order', 'order_id');
        await resetSequence('Image', 'image_id');

        console.log('✅ Sequences reset successfully');
    } catch (error) {
        console.error('⚠️ Could not reset sequences (might be expected if table empty or logic differs):', error.message);
    }
};
